os: osx
sudo: required
language: node_js
node_js:
  - '8.0.0'
  - '10.2.1'
  - '11.0.0'
script: 'npm run build-all && npm run test-all'
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master
